name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git .
          git fetch

      # Set up Node.js locally
      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          sudo apt-get install -y nodejs

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the project
      - name: Build the Project
        run: npm run build